{% set python_min = "3.10" %}
{% set name = "txl-local-kernels" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_local_kernels-{{ version }}.tar.gz
  sha256: 1a6f9413e31554c525731d5f95da5472b8bc5ce27fb41856abef506b8b6c1874

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - txl-kernel
    - pyzmq >=24.0.1
    - ipykernel

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_local_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  summary: TXL plugin for local kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
