{% set python_min = "3.10" %}
{% set name = "txl-local-kernels" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_local_kernels-{{ version }}.tar.gz
  sha256: cb62ffc81aa6d3caae53019c6ecbdf806f7ae2f1f61af444bf6b588075bd6fdf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - txl-kernel
    - pyzmq >=24.0.1
    - ipykernel

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_local_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  summary: TXL plugin for local kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
